version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      # Create an anonymous volume to prevent local node_modules from overwriting container's
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
